AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for Canvara Lambda functions.

Resources:
  CreatePost:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: create_post
      PackageType: Image
      ImageConfig:
        Command:
          - post.create_post_handler
      Role: arn:aws:iam::423429615815:role/service-role/lambda_basic_execution
    Metadata:
      Dockerfile: deploy/Dockerfile
      DockerContext: .
      DockerTag: v1
  ListPosts:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: list_posts
      PackageType: Image
      ImageConfig:
        Command:
          - post.list_posts_handler
      Role: arn:aws:iam::423429615815:role/service-role/lambda_basic_execution
    Metadata:
      Dockerfile: deploy/Dockerfile
      DockerContext: .
      DockerTag: v1
  GetPost:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get_post
      PackageType: Image
      ImageConfig:
        Command:
          - post.get_post_handler
      Role: arn:aws:iam::423429615815:role/service-role/lambda_basic_execution
    Metadata:
      Dockerfile: deploy/Dockerfile
      DockerContext: .
      DockerTag: v1
  UpdatePost:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: update_post
      PackageType: Image
      ImageConfig:
        Command:
          - post.update_post_handler
      Role: arn:aws:iam::423429615815:role/service-role/lambda_basic_execution
    Metadata:
      Dockerfile: deploy/Dockerfile
      DockerContext: .
      DockerTag: v1
  DeletePost:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: delete_post
      PackageType: Image
      ImageConfig:
        Command:
          - post.delete_post_handler
      Role: arn:aws:iam::423429615815:role/service-role/lambda_basic_execution
    Metadata:
      Dockerfile: deploy/Dockerfile
      DockerContext: .
      DockerTag: v1
  CreateCustomer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: create_customer
      PackageType: Image
      ImageConfig:
        Command:
          - customer.create_customer_handler
      Role: arn:aws:iam::423429615815:role/service-role/lambda_basic_execution
    Metadata:
      Dockerfile: deploy/Dockerfile
      DockerContext: .
      DockerTag: v1
  ListCustomers:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: list_customers
      PackageType: Image
      ImageConfig:
        Command:
          - customer.list_customers_handler
      Role: arn:aws:iam::423429615815:role/service-role/lambda_basic_execution
    Metadata:
      Dockerfile: deploy/Dockerfile
      DockerContext: .
      DockerTag: v1
  GetCustomer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get_customer
      PackageType: Image
      ImageConfig:
        Command:
          - customer.get_customer_handler
      Role: arn:aws:iam::423429615815:role/service-role/lambda_basic_execution
    Metadata:
      Dockerfile: deploy/Dockerfile
      DockerContext: .
      DockerTag: v1
  UpdateCustomer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: update_customer
      PackageType: Image
      ImageConfig:
        Command:
          - customer.update_customer_handler
      Role: arn:aws:iam::423429615815:role/service-role/lambda_basic_execution
    Metadata:
      Dockerfile: deploy/Dockerfile
      DockerContext: .
      DockerTag: v1
  DeleteCustomer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: delete_customer
      PackageType: Image
      ImageConfig:
        Command:
          - customer.delete_customer_handler
      Role: arn:aws:iam::423429615815:role/service-role/lambda_basic_execution
    Metadata:
      Dockerfile: deploy/Dockerfile
      DockerContext: .
      DockerTag: v1
  CreateUser:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: create_user
      PackageType: Image
      ImageConfig:
        Command:
          - user.create_user_handler
      Role: arn:aws:iam::423429615815:role/service-role/lambda_basic_execution
    Metadata:
      Dockerfile: deploy/Dockerfile
      DockerContext: .
      DockerTag: v1
  ListUsers:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: list_users
      PackageType: Image
      ImageConfig:
        Command:
          - user.list_users_handler
      Role: arn:aws:iam::423429615815:role/service-role/lambda_basic_execution
    Metadata:
      Dockerfile: deploy/Dockerfile
      DockerContext: .
      DockerTag: v1
  GetUser:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get_user
      PackageType: Image
      ImageConfig:
        Command:
          - user.get_user_handler
      Role: arn:aws:iam::423429615815:role/service-role/lambda_basic_execution
    Metadata:
      Dockerfile: deploy/Dockerfile
      DockerContext: .
      DockerTag: v1
  UpdateUser:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: update_user
      PackageType: Image
      ImageConfig:
        Command:
          - user.update_user_handler
      Role: arn:aws:iam::423429615815:role/service-role/lambda_basic_execution
    Metadata:
      Dockerfile: deploy/Dockerfile
      DockerContext: .
      DockerTag: v1
  DeleteUser:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: delete_user
      PackageType: Image
      ImageConfig:
        Command:
          - user.delete_user_handler
      Role: arn:aws:iam::423429615815:role/service-role/lambda_basic_execution
    Metadata:
      Dockerfile: deploy/Dockerfile
      DockerContext: .
      DockerTag: v1