version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "canvara-prototype"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-132yboqq4w0d0"
s3_prefix = "canvara-prototype"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
