AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for Canvara Lambda functions.

Resources:
  PostOperations:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: post_operations
      PackageType: Image
      ImageConfig:
        Command:
          - post.post_operations_handler
      Role: arn:aws:iam::423429615815:role/service-role/lambda_basic_execution
    Metadata:
      Dockerfile: deploy/Dockerfile
      DockerContext: .
      DockerTag: v1
  CustomerOperations:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: customer_operations
      PackageType: Image
      ImageConfig:
        Command:
          - customer.customer_operations_handler
      Role: arn:aws:iam::423429615815:role/service-role/lambda_basic_execution
    Metadata:
      Dockerfile: deploy/Dockerfile
      DockerContext: .
      DockerTag: v1
  UserOperations:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user_operations
      PackageType: Image
      ImageConfig:
        Command:
          - user.user_operations_handler
      Role: arn:aws:iam::423429615815:role/service-role/lambda_basic_execution
    Metadata:
      Dockerfile: deploy/Dockerfile
      DockerContext: .
      DockerTag: v1
  CreateApplication:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: create_application
      PackageType: Image
      ImageConfig:
        Command:
          - application.create_application_handler
      Role: arn:aws:iam::423429615815:role/service-role/lambda_basic_execution
    Metadata:
      Dockerfile: deploy/Dockerfile
      DockerContext: .
      DockerTag: v1
  ListApplicationsByPost:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: list_applications_by_post
      PackageType: Image
      ImageConfig:
        Command:
          - application.list_applications_by_post_handler
      Role: arn:aws:iam::423429615815:role/service-role/lambda_basic_execution
    Metadata:
      Dockerfile: deploy/Dockerfile
      DockerContext: .
      DockerTag: v1
  ListApplicationsByApplicant:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: list_applications_by_applicant
      PackageType: Image
      ImageConfig:
        Command:
          - application.list_applications_by_applicant_handler
      Role: arn:aws:iam::423429615815:role/service-role/lambda_basic_execution
    Metadata:
      Dockerfile: deploy/Dockerfile
      DockerContext: .
      DockerTag: v1
  GetApplication:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get_application
      PackageType: Image
      ImageConfig:
        Command:
          - application.get_application_handler
      Role: arn:aws:iam::423429615815:role/service-role/lambda_basic_execution
    Metadata:
      Dockerfile: deploy/Dockerfile
      DockerContext: .
      DockerTag: v1
  UpdateApplication:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: update_application
      PackageType: Image
      ImageConfig:
        Command:
          - application.update_application_handler
      Role: arn:aws:iam::423429615815:role/service-role/lambda_basic_execution
    Metadata:
      Dockerfile: deploy/Dockerfile
      DockerContext: .
      DockerTag: v1
  DeleteApplication:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: delete_application
      PackageType: Image
      ImageConfig:
        Command:
          - application.delete_application_handler
      Role: arn:aws:iam::423429615815:role/service-role/lambda_basic_execution
    Metadata:
      Dockerfile: deploy/Dockerfile
      DockerContext: .
      DockerTag: v1