AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for Canvara Lambda functions.

Resources:
  PostOperations:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: post_operations
      PackageType: Image
      ImageConfig:
        Command:
          - post.post_operations_handler
      Role: arn:aws:iam::423429615815:role/service-role/lambda_basic_execution
    Metadata:
      Dockerfile: deploy/Dockerfile
      DockerContext: .
      DockerTag: v1
  CustomerOperations:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: customer_operations
      PackageType: Image
      ImageConfig:
        Command:
          - customer.customer_operations_handler
      Role: arn:aws:iam::423429615815:role/service-role/lambda_basic_execution
    Metadata:
      Dockerfile: deploy/Dockerfile
      DockerContext: .
      DockerTag: v1
  UserOperations:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user_operations
      PackageType: Image
      ImageConfig:
        Command:
          - user.user_operations_handler
      Role: arn:aws:iam::423429615815:role/service-role/lambda_basic_execution
    Metadata:
      Dockerfile: deploy/Dockerfile
      DockerContext: .
      DockerTag: v1
  ApplicationOperations:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: application_operations
      PackageType: Image
      ImageConfig:
        Command:
          - application.application_operations_handler
      Role: arn:aws:iam::423429615815:role/service-role/lambda_basic_execution
    Metadata:
      Dockerfile: deploy/Dockerfile
      DockerContext: .
      DockerTag: v1
