openapi: 3.0.0
info:
  title: Canvara Backend API
  version: 0.1.1
servers: []
tags:
  - name: applications
  - name: customers
  - name: onboarding
  - name: posts
  - name: users
paths:
  /customers:
    get:
      summary: List all customers
      tags:
        - customers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
              examples: {}
      operationId: list_customers
      description: ''
      security:
        - AWSCognitoCanvaraPrototype: []
    post:
      summary: Add a new customer
      tags:
        - customers
      operationId: create_customer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
      security:
        - AWSCognitoCanvaraPrototype: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
  '/customers/{customer_id}':
    parameters:
      - schema:
          type: string
        name: customer_id
        in: path
        required: true
    get:
      summary: Get customer details
      tags:
        - customers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
      operationId: get_customer
      security:
        - AWSCognitoCanvaraPrototype: []
    delete:
      summary: Delete a customer
      tags:
        - customers
      operationId: delete_customer
      responses:
        '200':
          description: OK
      security:
        - AWSCognitoCanvaraPrototype: []
  '/customers/{customer_id}/users':
    parameters:
      - schema:
          type: string
        name: customer_id
        in: path
        required: true
    get:
      summary: List all users for a customer
      tags:
        - users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
      operationId: list_users
      security:
        - AWSCognitoCanvaraPrototype: []
    post:
      summary: Add a new user for a customer
      tags:
        - users
      operationId: create_user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      security:
        - AWSCognitoCanvaraPrototype: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                name:
                  type: string
                title:
                  type: string
                profile_picture_url:
                  type: string
                skills:
                  type: array
                  items:
                    $ref: '#/components/schemas/SkillWithLevel'
                desired_skills:
                  type: array
                  items:
                    $ref: '#/components/schemas/Skill'
              required:
                - user_id
                - name
  /posts:
    get:
      summary: List all posts
      tags:
        - posts
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
      operationId: list_posts
      security:
        - AWSCognitoCanvaraPrototype: []
    post:
      summary: Add a new post
      tags:
        - posts
      operationId: create_post
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
      security:
        - AWSCognitoCanvaraPrototype: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                summary:
                  type: string
                task_owner_id:
                  type: string
                description:
                  type: string
                size:
                  type: string
                target_date:
                  type: string
              required:
                - summary
  '/posts/{post_id}':
    parameters:
      - schema:
          type: string
        name: post_id
        in: path
        required: true
    get:
      summary: Get details of a post
      tags:
        - posts
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
      operationId: get_post
      security:
        - AWSCognitoCanvaraPrototype: []
    put:
      summary: Update details of a post
      tags:
        - posts
      operationId: update_post
      responses:
        '200':
          description: OK
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
      security:
        - AWSCognitoCanvaraPrototype: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                task_owner_id:
                  type: string
                summary:
                  type: string
                description:
                  type: string
                size:
                  type: string
                target_date:
                  type: string
    delete:
      summary: Delete a post
      tags:
        - posts
      operationId: delete_post
      responses:
        '200':
          description: OK
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
      security:
        - AWSCognitoCanvaraPrototype: []
  '/posts/{post_id}/applications':
    get:
      summary: List all applications for a post
      tags:
        - applications
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Application'
      operationId: list_applications_by_post
      security:
        - AWSCognitoCanvaraPrototype: []
    post:
      summary: Add a new application for a post
      operationId: create_application
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Application'
      security:
        - AWSCognitoCanvaraPrototype: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
      tags:
        - applications
    parameters:
      - schema:
          type: string
        name: post_id
        in: path
        required: true
  /applications:
    get:
      summary: List all applications
      tags:
        - applications
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Application'
      operationId: list_applications_by_applicant
      security:
        - AWSCognitoCanvaraPrototype: []
  '/applications/{application_id}':
    parameters:
      - schema:
          type: string
        name: application_id
        in: path
        required: true
    get:
      summary: Get details of an application
      tags:
        - applications
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Application'
      operationId: get_application
      security:
        - AWSCognitoCanvaraPrototype: []
    put:
      summary: Update details of an application
      operationId: update_application
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Application'
      security:
        - AWSCognitoCanvaraPrototype: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
      tags:
        - applications
    delete:
      summary: Delete an application
      operationId: delete_application
      responses:
        '200':
          description: OK
      security:
        - AWSCognitoCanvaraPrototype: []
      tags:
        - applications
  '/users/{user_id}':
    parameters:
      - schema:
          type: string
        name: user_id
        in: path
        required: true
    get:
      summary: Get user details
      tags:
        - users
      operationId: get_user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      security:
        - AWSCognitoCanvaraPrototype: []
    put:
      summary: Update details of a user
      tags:
        - users
      operationId: update_user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      security:
        - AWSCognitoCanvaraPrototype: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                title:
                  type: string
                profile_picture_url:
                  type: string
                skills:
                  type: array
                  items:
                    $ref: '#/components/schemas/SkillWithLevel'
                desired_skills:
                  type: array
                  items:
                    $ref: '#/components/schemas/Skill'
  /onboarding/product_preferences:
    get:
      summary: List all products that user can select
      tags:
        - onboarding
      operationId: list_products
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductPreference'
      security:
        - AWSCognitoCanvaraPrototype: []
    post:
      summary: Set product preferences during onboarding
      tags:
        - onboarding
      operationId: set_product_preferences
      responses:
        '204':
          description: No Content
      security:
        - AWSCognitoCanvaraPrototype: []
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/ProductPreference'
  /onboarding/skills:
    post:
      summary: Set skills during onboarding
      tags:
        - onboarding
      operationId: set_skills
      responses:
        '204':
          description: No Content
      security:
        - AWSCognitoCanvaraPrototype: []
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/SkillWithLevel'
  /onboarding/desired_skills:
    post:
      summary: Set desired skills during onboarding
      tags:
        - onboarding
      operationId: set_desired_skills
      responses:
        '204':
          description: No Content
      security:
        - AWSCognitoCanvaraPrototype: []
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Skill'
  /skills:
    get:
      summary: Search skills
      tags:
        - onboarding
      operationId: search_skills
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Skill'
      security:
        - AWSCognitoCanvaraPrototype: []
      parameters:
        - schema:
            type: string
          in: query
          name: q
          required: true
          description: The search query
components:
  schemas:
    Customer:
      title: Customer
      type: object
      x-examples: {}
      properties:
        customer_id:
          type: string
        name:
          type: string
      required:
        - customer_id
        - name
    User:
      title: User
      type: object
      properties:
        customer_id:
          type: string
        user_id:
          type: string
        name:
          type: string
        title:
          type: string
        profile_picture_url:
          type: string
        customer_name:
          type: string
        product_preferences:
          type: array
          items:
            $ref: '#/components/schemas/ProductPreference'
        skills:
          type: array
          items:
            $ref: '#/components/schemas/SkillWithLevel'
        desired_skills:
          type: array
          items:
            $ref: '#/components/schemas/Skill'
      required:
        - customer_id
        - user_id
        - name
    Post:
      title: Post
      type: object
      properties:
        customer_id:
          type: string
        post_id:
          type: string
        post_owner_id:
          type: string
        task_owner_id:
          type: string
        summary:
          type: string
        description:
          type: string
        size:
          type: string
        target_date:
          type: string
        created_at:
          type: string
        last_updated_at:
          type: string
      required:
        - customer_id
        - post_id
        - post_owner_id
        - task_owner_id
        - summary
    Application:
      title: Application
      type: object
      properties:
        post_id:
          type: string
        applicant_id:
          type: string
        application_id:
          type: string
        description:
          type: string
    Skill:
      title: Skill
      type: object
      properties:
        skill_id:
          type: string
        name:
          type: string
        custom:
          type: boolean
      required:
        - skill_id
    SkillWithLevel:
      title: SkillWithLevel
      allOf:
        - $ref: '#/components/schemas/Skill'
        - type: object
          properties:
            level:
              type: integer
    ProductPreference:
      title: ProductPreference
      type: object
      properties:
        product_id:
          type: string
        name:
          type: string
      required:
        - product_id
        - name
  securitySchemes:
    AWSCognitoCanvaraPrototype:
      type: http
      scheme: bearer
