# This workflow will upload the latest apis being supported by the backend code

name: API documentation update job

on:
  push:
    branches: [ main ]
    paths: 'apis/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        npm install
        npx redoc-cli bundle apis/api.yaml -o api.html
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
        
    - name: uploaded the api file to S3
      run: |
        aws s3 ls
        aws s3 cp api.html s3://docs.canvara.com/api.html
