# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Stage EC2 Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f pip_requirements.txt ]; then pip install -r pip_requirements.txt; fi
        cd /home/ubuntu/actions-runner/canvara/prototype/prototype/src/backend/db
        alembic upgrade head
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pylint
      run: |
        if [ -f pip_test_requirements.txt ]; then pip install -r pip_test_requirements.txt; fi
        #find . -name '*.py' -exec pylint {} \;
        pylint --rcfile .pylintrc src/backend
    #- name: Test with pytest
      #run: |
        #pytest
        

