# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Stage EC2 Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies & Upgrade database
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f pip_requirements.txt ]; then pip install -r pip_requirements.txt; fi
        export PYTHONPATH=/home/ubuntu/actions-runner/canvara/prototype/prototype/src
        export CANVARA_CONFIGS_DIR=/home/ubuntu/actions-runner/canvara/prototype/prototype/configs
        export CANVARA_ENV=stage
        cd /home/ubuntu/actions-runner/canvara/prototype/prototype/src/backend/db
        alembic upgrade head
        

